lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    delete "/login", AuthenticationController, :logout
    get "/login", AuthenticationController, :index
    post "/login", AuthenticationController, :create 
    resources "/likes", LikeController, except: [:new, :edit]
    resources "/follows", FollowController, except: [:index, :show]
    resources "/users", UserController
    resources "/posts", DisplayPostController
    get "/", AuthenticationController, :index
  end

  scope "/api", MicroblogWeb do
    pipe_through :api
    resources "/posts", PostController, except: [:new, :edit]
  end
end

lib/microblog_web/controllers/display_post_controller.ex
defmodule MicroblogWeb.DisplayPostController do
  use MicroblogWeb, :controller

  alias Microblog.Messages
  alias Microblog.Messages.Post

  def index(conn, _params) do
    user_id = get_session(conn, :user_id)
    if user_id do
      posts = Messages.list_posts(user_id)
    else 
      posts = Messages.list_posts()
    end
    changeset = Messages.change_post(%Post{})
    render(conn, "index_and_post.html", posts: posts, changeset: changeset)
  end

  def show(conn, %{"id" => id }) do

    post = Messages.get_post!(id)
    render(conn, "show.html", post: post)
  end

  def new(conn, _params) do
    changeset = Messages.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    user_id = get_session(conn, :user_id)
    post_params = Map.put(post_params, "user_id", user_id)
    case Messages.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: post_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def shows(conn, %{"id" => id}) do
    post = Messages.get_post!(id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Messages.get_post!(id)
    changeset = Messages.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Messages.get_post!(id)

    case Messages.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: post_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Messages.get_post!(id)
    {:ok, _post} = Messages.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: post_path(conn, :index))
  end
end

lib/microblog_web/views/display_post_view.ex
defmodule MicroblogWeb.DisplayPostView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/display_post/edit.html.eex
<h2>Edit Post</h2>

<%= render "form.html", Map.put(assigns, :action, display_post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: display_post_path(@conn, :index) %></span>

lib/microblog_web/templates/display_post/form.html.eex
<%= if @current_user do %>
<h2>New Post</h2>
<meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
<textarea id="post-text" class="form-control"></textarea>
<button id="post-add-button" class="btn btn-primary">Add Post</button>
<% end %>

lib/microblog_web/templates/display_post/index.html.eex
<%= if @current_user do %>
  <h2>Posts By People You Follow</h2>
<% else %>
  <h2>Posts By Everyone</h2>
<% end %>

  <div id="post-target"
     data-path="<%= post_path(@conn, :index) %>">
  &nbsp;
  </div>


<script id="post-template" type="text/x-handlebars-template">
<table class="table" id="postTable">
  <thead>
    <tr>
      <th>Username</th>
      <th>Post</th>
      <th>Likes</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {{#each data}}
  <tr>
      <td>
      {{#if username}}
        {{username}}
      {{else}}
        N/A
      {{/if}}
      </td>
      <td>
        {{text}}
      </td>
      <td>
        {{likes}}
      </td>
      <td>
      <a href="/posts/{{id}}" class="btn btn-primary"> Show </a>
      </td>
      {{/each}}
  </tr>
  </tbody>
</table>
</script>

lib/microblog_web/templates/display_post/index_and_post.html.eex
<%= render "form.html", Map.put(assigns, :action, display_post_path(@conn, :create)) %>
<%= render "index.html", assigns %>

lib/microblog_web/templates/display_post/new.html.eex
<h2>New Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :create)) %>

<span><%= link "Back", to: display_post_path(@conn, :index) %></span>

lib/microblog_web/templates/display_post/show.html.eex
<meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
<h2>Show Post</h2>

<ul>

  <li>
    <strong>Text:</strong>
    <%= @post.text %>

  </li>

  <li>
    <strong>Users Id:</strong>
    <%= @post.id %>
    
  </li>

</ul>

<%= if @current_user do %>
<% end %>
<div id="post-likes"
     data-path="<%= like_path(@conn, :index) %>"
     data-post_id="<%= @post.id %>">
  &nbsp;
</div>

<script id="likes-template" type="text/x-handlebars-template">
  {{#if liked}}
    <button id="like-button" class="btn btn-danger">Unlike!</button>
  {{else}}
    <button id="like-button" class="btn btn-primary">Like!</button>
  {{/if}}

	<h2>Liked by</h2>

	<ul>
		{{#each data}}
	  <li>{{username}}</li>
	  	 {{/each}}
	</ul>
</script>

<span><%= link "Back", to: display_post_path(@conn, :index), class: "btn btn-primary" %></span>