lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    delete "/login", AuthenticationController, :logout
    get "/login", AuthenticationController, :index
    post "/login", AuthenticationController, :create 
    resources "/likes", LikeController, except: [:new, :edit]
    resources "/follows", FollowController, except: [:index, :show]
    resources "/users", UserController
    resources "/posts", DisplayPostController
    get "/", AuthenticationController, :index
  end

  scope "/api", MicroblogWeb do
    pipe_through :api
    resources "/posts", PostController, except: [:new, :edit]
  end
end

lib/microblog/account/user.ex
defmodule Microblog.Account.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Account.User


  schema "users" do
    field :first_name, :string
    field :last_name, :string
    field :nickname, :string
    field :username, :string
    field :password_hash, :string


    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    many_to_many :following, User, join_through: Microblog.Account.Follow, join_keys: [user_id: :id, following_id: :id]

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:username, :first_name, :last_name, :nickname, :password, :password_confirmation])
    |> validate_confirmation(:password)
    |> validate_password(:password)
    |> put_pass_hash()
    |> validate_required([:username, :first_name, :last_name, :nickname, :password_hash])
  end

  # Password validation
  # From Comeonin docs
  def validate_password(changeset, field, options \\ []) do
    validate_change(changeset, field, fn _, password ->
      case valid_password?(password) do
        {:ok, _} -> []
        {:error, msg} -> [{field, options[:message] || msg}]
      end
    end)
  end

  def put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, Comeonin.Argon2.add_hash(password))
  end
  def put_pass_hash(changeset), do: changeset


  def valid_password?(password) when byte_size(password) > 7 do
    {:ok, password}
  end
  def valid_password?(_), do: {:error, "The password is too short"}
end

lib/microblog_web/controllers/user_controller.ex
defmodule MicroblogWeb.UserController do
  use MicroblogWeb, :controller
  alias Microblog.Account
  alias Microblog.Account.User
  alias Microblog.Account.Follow

  def index(conn, _params) do
    users = Account.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Account.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Account.create_user(user_params) do
      {:ok, user} ->
        Account.create_follow(%{user_id: user.id, following_id: user.id})
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Account.get_user!(id)
    is_followed = 
      case conn.assigns.current_user do
        nil -> nil
        _ -> Account.is_following(conn.assigns.current_user_id, id)
      end

    changeset = Account.change_follow(%Follow{})
    render(conn, "show.html", user: user, changeset: changeset, is_followed: is_followed)
  end

  def edit(conn, %{"id" => id}) do
    user = Account.get_user!(id)
    changeset = Account.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Account.get_user!(id)

    case Account.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Account.get_user!(id)
    {:ok, _user} = Account.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/microblog_web/views/user_view.ex
defmodule MicroblogWeb.UserView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/follow_form.html.eex
<%= form_for @changeset, @action, fn f -> %>

  <div class="form-group">
    <%= hidden_input f, :following_id, class: "form-control", value: @user.id %>
  </div>

  <div class="form-group">
    <%= submit "Follow", class: "btn btn-primary" %>
  </div>
<% end %>

lib/microblog_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :first_name, class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>

  <div class="form-group">
    <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= label f, :nickname, class: "control-label" %>
    <%= text_input f, :nickname, class: "form-control" %>
    <%= error_tag f, :nickname %>
  </div>


  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

lib/microblog_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Nickname</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.nickname %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-primary" %></span>
        <%= if @current_user do %>
        <%= if @current_user.id == user.id do %>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-primary" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></span>
        <% end %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new), class: "btn btn-primary"%></span>

lib/microblog_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary"%></span>

lib/microblog_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </li>

  <li>
    <strong>Nickname:</strong>
    <%= @user.nickname %>
  </li>

</ul>
<%= if @current_user do %>
<%= if @is_followed do %>
  <span><%= link "Unfollow", to: follow_path(@conn, :delete, @user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></span>
<% else %>
  <%= render "follow_form.html", Map.put(assigns, :action, follow_path(@conn, :create)) %>
<% end %>
<% end %>
<%= if @current_user do %>
<%= if @current_user.id == @user.id do %>
<span><%= link "Edit", to: user_path(@conn, :edit, @user), class: "btn btn-primary" %></span>
<% end %>
<% end %>
<span><%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary" %></span>

<h2>Users <%= @user.username %> Is Following </h2>
<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Nickname</th>
      <%= if @current_user do %>
      <%= if @current_user.id == @user.id do %>
      <th></th>
      <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= for follow <- @user.following do %>
        <tr>
          <td><%= follow.username %></td>
          <td><%= follow.first_name %></td>
          <td><%= follow.last_name %></td>
          <td><%= follow.nickname %></td>
          <%= if @current_user do %>
          <%= if @current_user.id == @user.id do %>
          <td class="text-right">
            <span><%= link "Unfollow", to: follow_path(@conn, :delete, follow), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></span>
          </td>
          <% end %>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>