lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack
    delete "/login", AuthenticationController, :logout
    get "/login", AuthenticationController, :index
    post "/login", AuthenticationController, :create 
    resources "/likes", LikeController, except: [:new, :edit]
    resources "/follows", FollowController, except: [:index, :show]
    resources "/users", UserController
    resources "/posts", DisplayPostController
    get "/", AuthenticationController, :index
  end

  scope "/api", MicroblogWeb do
    pipe_through :api
    resources "/posts", PostController, except: [:new, :edit]
  end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Hello Microblog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Rick's Microblog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <%= if @current_user do %>
                    <li class="nav-item active">
                        <span><%= link "Profile", to: user_path(@conn, :show, @current_user), class: "nav-link" %></span>
                    </li>
                    <% end %>
                    <li class="nav-item active">
                        <span><%= link "Users", to: user_path(@conn, :index), class: "nav-link" %></span>
                    </li>
                    <li class="nav-item">
                        <span><%= link "Posts", to: display_post_path(@conn, :index), class: "nav-link" %></span>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= if @current_user do %>
                            <span>
                                <%= link(@logout_message, to: authentication_path(@conn, :logout), class: "nav-link", method: "delete") %>                           
                            </span>
                        <% else %> 
                            <span><%= link("Sign In", to: authentication_path(@conn, :index), class: "nav-link") %></span>
                        <% end %>
                    </li>
                </ul>
            </div>
        </nav>
    <div class="container">
        <span class="logo"></span>
        </header>
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert">
            <%= get_flash(@conn, :info) %>
          </p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert">
            <%= get_flash(@conn, :error) %>
          </p>
        <% end %>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
    </div>
    <!-- /container -->
    <%= if @current_user do %>
        <script type="text/javascript" >var currentUser = <%= @current_user.id %> </script>
    <% end %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>